CREATE TABLE IF NOT EXISTS USUARIO (
	id SERIAL PRIMARY KEY,
	nome VARCHAR(255) NOT NULL,
	email VARCHAR(255) NOT NULL UNIQUE,
	senha VARCHAR(255) NOT NULL,
	tipo VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS PRODUTOS (
	id SERIAL PRIMARY KEY,
	nome VARCHAR(255) NOT NULL,
	urlImage TEXT
);
